name = "miniflare-typescript-esbuild"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
kv_namespaces = [
  { binding = "counter", id = "", preview_id = "" },
]

[build]
command = "npm run build"
[build.upload]
format = "service-worker"
