name = "worker-typescript-local"
main = "build/index.js"
workers_dev = true
compatibility_date = "2022-10-17"

[build]
command = "npm run build"

[env.production]
name = "worker-typescript"
[[env.production.kv_namespaces]]
binding = "COUNTER"
id = "3f04be9cee4445d29a5a331fee98e78b"
